/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kafka.lab.events.v1;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UploadCompletedResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3707516183549561477L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UploadCompletedResult\",\"namespace\":\"kafka.lab.events.v1\",\"fields\":[{\"name\":\"conversationId\",\"type\":\"string\"},{\"name\":\"csvfile\",\"type\":\"string\"},{\"name\":\"audiofile\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UploadCompletedResult> ENCODER =
      new BinaryMessageEncoder<UploadCompletedResult>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UploadCompletedResult> DECODER =
      new BinaryMessageDecoder<UploadCompletedResult>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UploadCompletedResult> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UploadCompletedResult> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UploadCompletedResult> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UploadCompletedResult>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UploadCompletedResult to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UploadCompletedResult from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UploadCompletedResult instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UploadCompletedResult fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence conversationId;
   private java.lang.CharSequence csvfile;
   private java.lang.CharSequence audiofile;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UploadCompletedResult() {}

  /**
   * All-args constructor.
   * @param conversationId The new value for conversationId
   * @param csvfile The new value for csvfile
   * @param audiofile The new value for audiofile
   */
  public UploadCompletedResult(java.lang.CharSequence conversationId, java.lang.CharSequence csvfile, java.lang.CharSequence audiofile) {
    this.conversationId = conversationId;
    this.csvfile = csvfile;
    this.audiofile = audiofile;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return conversationId;
    case 1: return csvfile;
    case 2: return audiofile;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: conversationId = (java.lang.CharSequence)value$; break;
    case 1: csvfile = (java.lang.CharSequence)value$; break;
    case 2: audiofile = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'conversationId' field.
   * @return The value of the 'conversationId' field.
   */
  public java.lang.CharSequence getConversationId() {
    return conversationId;
  }


  /**
   * Sets the value of the 'conversationId' field.
   * @param value the value to set.
   */
  public void setConversationId(java.lang.CharSequence value) {
    this.conversationId = value;
  }

  /**
   * Gets the value of the 'csvfile' field.
   * @return The value of the 'csvfile' field.
   */
  public java.lang.CharSequence getCsvfile() {
    return csvfile;
  }


  /**
   * Sets the value of the 'csvfile' field.
   * @param value the value to set.
   */
  public void setCsvfile(java.lang.CharSequence value) {
    this.csvfile = value;
  }

  /**
   * Gets the value of the 'audiofile' field.
   * @return The value of the 'audiofile' field.
   */
  public java.lang.CharSequence getAudiofile() {
    return audiofile;
  }


  /**
   * Sets the value of the 'audiofile' field.
   * @param value the value to set.
   */
  public void setAudiofile(java.lang.CharSequence value) {
    this.audiofile = value;
  }

  /**
   * Creates a new UploadCompletedResult RecordBuilder.
   * @return A new UploadCompletedResult RecordBuilder
   */
  public static kafka.lab.events.v1.UploadCompletedResult.Builder newBuilder() {
    return new kafka.lab.events.v1.UploadCompletedResult.Builder();
  }

  /**
   * Creates a new UploadCompletedResult RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UploadCompletedResult RecordBuilder
   */
  public static kafka.lab.events.v1.UploadCompletedResult.Builder newBuilder(kafka.lab.events.v1.UploadCompletedResult.Builder other) {
    if (other == null) {
      return new kafka.lab.events.v1.UploadCompletedResult.Builder();
    } else {
      return new kafka.lab.events.v1.UploadCompletedResult.Builder(other);
    }
  }

  /**
   * Creates a new UploadCompletedResult RecordBuilder by copying an existing UploadCompletedResult instance.
   * @param other The existing instance to copy.
   * @return A new UploadCompletedResult RecordBuilder
   */
  public static kafka.lab.events.v1.UploadCompletedResult.Builder newBuilder(kafka.lab.events.v1.UploadCompletedResult other) {
    if (other == null) {
      return new kafka.lab.events.v1.UploadCompletedResult.Builder();
    } else {
      return new kafka.lab.events.v1.UploadCompletedResult.Builder(other);
    }
  }

  /**
   * RecordBuilder for UploadCompletedResult instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UploadCompletedResult>
    implements org.apache.avro.data.RecordBuilder<UploadCompletedResult> {

    private java.lang.CharSequence conversationId;
    private java.lang.CharSequence csvfile;
    private java.lang.CharSequence audiofile;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(kafka.lab.events.v1.UploadCompletedResult.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.conversationId)) {
        this.conversationId = data().deepCopy(fields()[0].schema(), other.conversationId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.csvfile)) {
        this.csvfile = data().deepCopy(fields()[1].schema(), other.csvfile);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.audiofile)) {
        this.audiofile = data().deepCopy(fields()[2].schema(), other.audiofile);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing UploadCompletedResult instance
     * @param other The existing instance to copy.
     */
    private Builder(kafka.lab.events.v1.UploadCompletedResult other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.conversationId)) {
        this.conversationId = data().deepCopy(fields()[0].schema(), other.conversationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.csvfile)) {
        this.csvfile = data().deepCopy(fields()[1].schema(), other.csvfile);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.audiofile)) {
        this.audiofile = data().deepCopy(fields()[2].schema(), other.audiofile);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'conversationId' field.
      * @return The value.
      */
    public java.lang.CharSequence getConversationId() {
      return conversationId;
    }


    /**
      * Sets the value of the 'conversationId' field.
      * @param value The value of 'conversationId'.
      * @return This builder.
      */
    public kafka.lab.events.v1.UploadCompletedResult.Builder setConversationId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.conversationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'conversationId' field has been set.
      * @return True if the 'conversationId' field has been set, false otherwise.
      */
    public boolean hasConversationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'conversationId' field.
      * @return This builder.
      */
    public kafka.lab.events.v1.UploadCompletedResult.Builder clearConversationId() {
      conversationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'csvfile' field.
      * @return The value.
      */
    public java.lang.CharSequence getCsvfile() {
      return csvfile;
    }


    /**
      * Sets the value of the 'csvfile' field.
      * @param value The value of 'csvfile'.
      * @return This builder.
      */
    public kafka.lab.events.v1.UploadCompletedResult.Builder setCsvfile(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.csvfile = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'csvfile' field has been set.
      * @return True if the 'csvfile' field has been set, false otherwise.
      */
    public boolean hasCsvfile() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'csvfile' field.
      * @return This builder.
      */
    public kafka.lab.events.v1.UploadCompletedResult.Builder clearCsvfile() {
      csvfile = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'audiofile' field.
      * @return The value.
      */
    public java.lang.CharSequence getAudiofile() {
      return audiofile;
    }


    /**
      * Sets the value of the 'audiofile' field.
      * @param value The value of 'audiofile'.
      * @return This builder.
      */
    public kafka.lab.events.v1.UploadCompletedResult.Builder setAudiofile(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.audiofile = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'audiofile' field has been set.
      * @return True if the 'audiofile' field has been set, false otherwise.
      */
    public boolean hasAudiofile() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'audiofile' field.
      * @return This builder.
      */
    public kafka.lab.events.v1.UploadCompletedResult.Builder clearAudiofile() {
      audiofile = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UploadCompletedResult build() {
      try {
        UploadCompletedResult record = new UploadCompletedResult();
        record.conversationId = fieldSetFlags()[0] ? this.conversationId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.csvfile = fieldSetFlags()[1] ? this.csvfile : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.audiofile = fieldSetFlags()[2] ? this.audiofile : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UploadCompletedResult>
    WRITER$ = (org.apache.avro.io.DatumWriter<UploadCompletedResult>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UploadCompletedResult>
    READER$ = (org.apache.avro.io.DatumReader<UploadCompletedResult>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.conversationId);

    out.writeString(this.csvfile);

    out.writeString(this.audiofile);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.conversationId = in.readString(this.conversationId instanceof Utf8 ? (Utf8)this.conversationId : null);

      this.csvfile = in.readString(this.csvfile instanceof Utf8 ? (Utf8)this.csvfile : null);

      this.audiofile = in.readString(this.audiofile instanceof Utf8 ? (Utf8)this.audiofile : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.conversationId = in.readString(this.conversationId instanceof Utf8 ? (Utf8)this.conversationId : null);
          break;

        case 1:
          this.csvfile = in.readString(this.csvfile instanceof Utf8 ? (Utf8)this.csvfile : null);
          break;

        case 2:
          this.audiofile = in.readString(this.audiofile instanceof Utf8 ? (Utf8)this.audiofile : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










